### ISSUE TITLE
when I run the file baseline/train.py, I got the following error

### ISSUE THREAD

**Issue by THHHomas** [ahangchen/rank-reid#10]
I download the resnet50 pretrained file and run "python baseline/train.py", got the following error :
Traceback (most recent call last):
  File "baseline/train.py", line 168, in <module>
    softmax_pretrain_on_dataset(source)
  File "baseline/train.py", line 161, in softmax_pretrain_on_dataset
    softmax_model_pretrain(train_list, train_dir, class_count, './source' + '_softmax_pretrain.h5')
  File "baseline/train.py", line 122, in softmax_model_pretrain
    steps_per_epoch=len(images) / batch_size + 1, epochs=40,
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 2224, in fit_generator
    class_weight=class_weight)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1877, in train_on_batch
    class_weight=class_weight)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected fc8 to have shape (715,) but got array with shape (5,)

but in the code:
 x = base_model.output
    x = Flatten(name='flatten')(x)
    x = Dropout(0.5)(x)
    x = Dense(input_dim=2048, units=715, activation='softmax', name='fc8', kernel_initializer=RandomNormal(mean=0.0, stddev=0.001))(x)
we set the output of Dense is 751.   could you please help me to solve the problem?

**Comment by THHHomas** [comment]
My python version is 2.7, tensorflow is 1.8 and keras is 2.1.5?
