### ISSUE TITLE
Evaluation Matrix in GPU computation

### ISSUE THREAD

**Issue by arnabk001** [ahangchen/rank-reid#18]
While running the code on Market 1501 dataset, the class count value in baseline/train.py is set to 751 while the number of ids in the dataset is 1501.
Also, there is no folder named 'probe' in the official market-1501 dataset. Do you mean the 'query' folder to be named as 'probe'?

**Comment by ahangchen** [comment]
The number of ids in the training set of Market1501 is 751. The number of ids in all the dataset is 1501, so we only need 751 classes when training.

Yes, query == probe, test == bounding_box_test.

We run the code for other datasets, so we uniform all the dataset's names in this style.

**Comment by arnabk001** [comment]
Trying to run baseline/evaluate.py and got this error

`Traceback (most recent call last):

  File "<ipython-input-7-707de8e74dd2>", line 12, in <module>
    test_predict(net, probe_path, gallery_path,  pid_path, score_path)

  File "<ipython-input-5-0134a0987c86>", line 27, in test_predict
    result, result_argsort = sort_similarity(query_f, test_f)

  File "<ipython-input-3-28f3e4fc21ff>", line 23, in sort_similarity
    result = similarity_matrix(query_f, test_f)

  File "<ipython-input-3-28f3e4fc21ff>", line 15, in similarity_matrix
    result = sess.run(tensor, {query_t: query_f, test_t: test_f})

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)

InternalError: Dst tensor is not initialized.
	 [[Node: _arg_Placeholder_536_0_1/_1 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_23__arg_Placeholder_536_0_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
	 [[Node: MatMul/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_25_MatMul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]`


This is due to memory overflow. Training in GTX 1060 Ti with 6GB VRAM. Any comments on how i can modify `similarity_matrix` to run it in my GPU?

**Comment by arnabk001** [comment]
I have tried reducing the query size and in that case memory allocation error is not there. but i get an error like this

`
Traceback (most recent call last):

  File "<ipython-input-7-07b64983bbc2>", line 12, in <module>
    test_predict(net, probe_path, gallery_path,  pid_path, score_path)

  File "<ipython-input-5-0134a0987c86>", line 27, in test_predict
    result, result_argsort = sort_similarity(query_f, test_f)

  File "<ipython-input-3-28f3e4fc21ff>", line 23, in sort_similarity
    result = similarity_matrix(query_f, test_f)

  File "<ipython-input-3-28f3e4fc21ff>", line 15, in similarity_matrix
    result = sess.run(tensor, {query_t: query_f, test_t: test_f})

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)

  File "C:\Users\VR LAB PC3\AppData\Local\conda\conda\envs\tfpy36\lib\site-packages\tensorflow\python\client\session.py", line 1104, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder_535:0', which has shape '(?, ?)'
`

Another thing to point out is there is no `avg_pool` layer in the model market_softmax_pretrain.h5
Any help would be highly appreciated.

**Comment by ahangchen** [comment]
Refer to [Zhedong's pytorch baseline](https://github.com/layumi/Person_reID_baseline_pytorch), we write a memory-friendly [evaluation script](https://github.com/ahangchen/rank-reid/blob/master/baseline/eval_on_result.py), when you generate ranking id tables, for example named with 'market_rank_pid.txt', you can use `python3 eval_on_result.py --target_dataset_path /home/cwh/coding/dataset/market --pid_path market_rank_pid.txt --result_path market_result.log` to compute map and rank1, rank5, rank10.
